// Image assets for the market tracker application

// Placeholder images
export { default as noImagePlaceholder } from './no-image-placeholder.svg';

// Image upload constants
export const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp'];
export const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

// Allowed market tags
export const ALLOWED_MARKET_TAGS = [
  // Product types
  'local-produce',
  'fresh-produce',
  'organic',
  'handmade',
  'artisan',
  'vintage',
  'antique',
  'crafts',
  'food',
  'art',
  'jewelry',
  'clothing',
  'furniture',
  'plants',
  'flowers',
  'home-decor',
  'baked-goods',
  'farm-to-table',
  'toys',
  'kids-toys',
  'pottery',
  'ceramics',
  'upcycled',
  'upcycled-clothing',
  'houseware',
  'stickers',
  'soap',
  'body-care',
  'candles',
  'books',
  'magazines',
  'photography',
  'prints',
  'posters',
  'zines',
  'leather-goods',
  'woodwork',
  'metalwork',
  'glass-art',
  'textiles',
  'fiber-art',
  'paper-goods',
  'stationery',
  'crystals',
  'gemstones',
  'accessories',
  'bags',
  'purses',
  'shoes',
  'hats',
  'scarves',
  'sunglasses',
  'watches',
  'beauty',
  'skincare',
  'makeup',
  'wellness',
  'health',
  'fitness',
  'sports',
  'collectibles',
  'memorabilia',
  'novelty',
  'gifts',
  
  // Media formats
  'vinyl',
  'vhs',
  'cassette',
  'cds',
  'dvds',
  'records',
  
  // Food types
  'sushi',
  'pizza',
  'tacos',
  'bbq',
  'burgers',
  'coffee',
  'tea',
  'ice-cream',
  'desserts',
  'pastries',
  'donuts',
  'chocolate',
  'candy',
  'popcorn',
  'pretzels',
  'smoothies',
  'juice',
  'chinese-food',
  'korean-food',
  'japanese-food',
  'thai-food',
  'indian-food',
  'mexican-food',
  'italian-food',
  'greek-food',
  'mediterranean-food',
  'soul-food',
  'cajun-food',
  'caribbean-food',
  'filipino-food',
  'vietnamese-food',
  
  // Alternative & Subculture
  'gothic',
  'punk',
  'emo',
  'anime',
  'manga',
  'cosplay',
  'kawaii',
  'y2k',
  'retro',
  '2000s',
  '90s',
  '80s',
  '70s',
  'bohemian',
  'hippie',
  'steampunk',
  'cyberpunk',
  'vaporwave',
  'indie',
  'alternative',
  'underground',
  'counter-culture',
  'streetwear',
  'thrifting',
  'record-fair',
  'comics',
  'gaming',
  'tattoo',
  'skateboarding',
  'bmx',
  'metal',
  'rockabilly',
  'psychobilly',
  
  // Cultural & Ethnic
  'asian-market',
  'latin-market',
  'european-market',
  'african-market',
  'middle-eastern',
  'caribbean',
  'indigenous',
  
  // Community & Vendors
  'collective',
  'new-vendors',
  'local-vendors',
  'student-vendors',
  'emerging-artists',
  'small-business',
  'minority-owned',
  'women-owned',
  'lgbtq-owned',
  'veteran-owned',
  'non-profit',
  'charity',
  'fundraiser',
  
  // Alternative Market Types
  'gallery',
  'art-show',
  'art-market',
  'pop-up',
  'popup-market',
  'flea-market',
  'swap-meet',
  'garage-sale',
  'yard-sale',
  'estate-sale',
  'auction',
  'bazaar',
  'fair',
  'festival',
  'exhibition',
  'showcase',
  'trunk-show',
  'sample-sale',
  'clearance',
  'warehouse-sale',
  
  // Seasonal & Holiday
  'christmas',
  'halloween',
  'easter',
  'valentines',
  'thanksgiving',
  'spring',
  'summer',
  'fall',
  'winter',
  'holiday',
  
  // Time-based
  'morning',
  'afternoon',
  'evening',
  'late-night',
  'weekend',
  'weekday',
  
  // Niche & Spiritual
  'tarot',
  'astrology',
  'metaphysical',
  'spiritual',
  'reiki',
  'energy-healing',
  'crystal-healing',
  'palmistry',
  'psychic',
  
  // Art Styles
  'modern-art',
  'contemporary',
  'street-art',
  'folk-art',
  'digital-art',
  'abstract',
  'surrealism',
  'illustration',
  'sculpture',
  'mixed-media',
  
  // Tech & Electronics
  'electronics',
  'vintage-tech',
  'retro-gaming',
  'video-games',
  'computer-parts',
  'cameras',
  'audio-equipment',
  'vinyl-records',
  
  // Music Genres
  'jazz',
  'hip-hop',
  'electronic-music',
  'folk-music',
  'country-music',
  'blues',
  'acoustic',
  'rock',
  'classical',
  'rnb',
  'reggae',
  'latin-music',
  
  // Price & Payment
  'budget-friendly',
  'affordable',
  'luxury',
  'high-end',
  'cash-only',
  'card-accepted',
  'free-admission',
  
  // Services
  'custom-orders',
  'made-to-order',
  'repairs',
  'alterations',
  'personalization',
  'on-site-customization',
  
  // Home & Garden
  'succulents',
  'herbs',
  'seeds',
  'garden-supplies',
  'planters',
  'landscaping',
  'indoor-plants',
  'outdoor-plants',
  
  // Weather & Logistics
  'rain-or-shine',
  'weather-permitting',
  'heated',
  'air-conditioned',
  
  // Fiber & Textile Arts
  'knitting',
  'crochet',
  'quilting',
  'embroidery',
  'weaving',
  'macrame',
  'sewing',
  'fiber-arts',
  
  // More Crafts
  'blacksmithing',
  'welding',
  'pottery-throwing',
  'glass-blowing',
  'wood-carving',
  'leather-working',
  
  // Pet Specific
  'pet-supplies',
  'dog-treats',
  'cat-toys',
  'pet-accessories',
  'pet-grooming',
  
  // Weddings & Events
  'wedding-vendors',
  'bridal',
  'event-planning',
  'party-supplies',
  'florist',
  
  // Kids Activities
  'kids-activities',
  'face-painting',
  'balloon-art',
  'magic-show',
  'storytelling',
  'bounce-house',
  
  // Educational
  'science',
  'educational',
  'stem',
  'workshops',
  'classes',
  'demos',
  'tutorials',
  'learn-to',
  
  // Literary
  'poetry',
  'spoken-word',
  'book-signing',
  'author-meet',
  'literary',
  
  // Beverages
  'kombucha',
  'craft-beer',
  'wine',
  'cocktails',
  'mocktails',
  'boba',
  'bubble-tea',
  'craft-soda',
  'fresh-pressed',
  
  // Dietary
  'vegan',
  'vegetarian',
  'gluten-free',
  'keto',
  'paleo',
  'dairy-free',
  'nut-free',
  'allergy-friendly',
  
  // Specific Foods
  'cheese',
  'bread',
  'honey',
  'jam',
  'pickles',
  'jerky',
  'nuts',
  'dried-fruit',
  'spices',
  'hot-sauce',
  'olive-oil',
  'maple-syrup',
  
  // Fashion Specific
  'denim',
  'leather-fashion',
  'vintage-clothing',
  'retro-fashion',
  'sustainable-fashion',
  'slow-fashion',
  'ethical-fashion',
  'upcycled-fashion',
  
  // Jewelry Types
  'handmade-jewelry',
  'vintage-jewelry',
  'costume-jewelry',
  'fine-jewelry',
  'beaded-jewelry',
  'silver-jewelry',
  'gold-jewelry',
  
  // Collecting
  'stamps',
  'coins',
  'sports-cards',
  'trading-cards',
  'action-figures',
  'dolls',
  'pins',
  'patches',
  'buttons',
  'keychains',
  
  // Outdoor & Adventure
  'camping',
  'hiking',
  'fishing',
  'hunting',
  'outdoor-gear',
  'survival',
  
  // DIY & Supplies
  'diy-supplies',
  'craft-supplies',
  'art-supplies',
  'fabric',
  'yarn',
  'beads',
  'tools',
  
  // Location & Vibe
  'urban',
  'suburban',
  'rural',
  'waterfront',
  'downtown',
  'neighborhood',
  'historic',
  'warehouse-district',
  'arts-district',
  
  // Accessibility
  'sensory-friendly',
  'autism-friendly',
  'quiet-hours',
  'asl-interpreter',
  'multilingual',
  
  // Age restrictions
  'all-ages',
  '18+',
  '19+',
  '20+',
  '21+',
  'adults-only',
  
  // Who It's For - Demographics & Audiences
  'families',
  'kids',
  'teens',
  'adults',
  'seniors',
  'couples',
  'singles',
  'date-night',
  'moms',
  'dads',
  'parents',
  'new-parents',
  'grandparents',
  'college-students',
  'teachers',
  'nurses',
  'military',
  'first-responders',
  'locals',
  'tourists',
  'visitors',
  'newcomers',
  'neighbors',
  'beginners',
  'collectors',
  'decorators',
  'chefs',
  'bakers',
  'gardeners',
  'pet-owners',
  'plant-parents',
  'book-lovers',
  'music-lovers',
  'art-lovers',
  'foodies',
  'coffee-lovers',
  'vintage-lovers',
  'thrill-seekers',
  'bargain-hunters',
  'eco-conscious',
  'minimalists',
  'diy-enthusiasts',
  'creatives',
  'entrepreneurs',
  'small-business-owners',
  'crafters',
  'makers',
  'hobbyists',
  
  // Amenities & Features
  'live-music',
  'family-friendly',
  'pet-friendly',
  'outdoor',
  'indoor',
  'covered',
  'free-entry',
  'parking',
  'wheelchair-accessible',
  'wifi',
  'atm',
  'food-court',
  'food-trucks',
  'eco-friendly',
  'sustainable',
  'zero-waste'
];

// Category placeholder images
export { default as farmersMarketImage } from './farmermarket.webp';
export { default as artsCraftsImage } from './artandcraft.webp';
export { default as fleaMarketImage } from './fleamarket.webp';
export { default as foodFestivalImage } from './foodfestival.webp';
export { default as craftShowImage } from './craftshow.webp';
export { default as communityEventImage } from './communityevent.webp';
export { default as holidayMarketImage } from './holidaymarket.webp';
export { default as nightMarketImage } from './nightmarket.webp';
export { default as streetFairImage } from './streetfair.webp';
export { default as vintageAntiqueImage } from './vintageandantique.webp';

// Helper to get image by category - returns relative URL for database storage
export const getCategoryImage = (category: string): string => {
  const imageMap: Record<string, string> = {
    'farmers-market': '/assets/images/farmermarket.webp',
    'arts-crafts': '/assets/images/artandcraft.webp',
    'flea-market': '/assets/images/fleamarket.webp',
    'food-festival': '/assets/images/foodfestival.webp',
    'craft-fair': '/assets/images/craftshow.webp',
    'community-event': '/assets/images/communityevent.webp',
    'holiday-market': '/assets/images/holidaymarket.webp',
    'night-market': '/assets/images/nightmarket.webp',
    'street-fair': '/assets/images/streetfair.webp',
    'vintage-antique': '/assets/images/vintageandantique.webp',
  };
  return imageMap[category] || '/assets/images/no-image-placeholder.svg';
};
